name: Construir e Publicar
on:
  push:
    branches-ignore:
      - gh-pages
  workflow_dispatch:
  pull_request:
jobs:
  build:
    name: Construir e Publicar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: '12'
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: '0'
          persist-credentials: false
          submodules: 'recursive'
      - name: Instalar
        run: npm install
      - name: Construir
        run: npm run build
      - name: Publicar
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: .vuepress/dist/
          clean: true
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: '12'
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: '0'
          submodules: 'recursive'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint-ci
